# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: security_login
                check_path: security_login_check
                default_target_path: homepage
                remember_me: true
            logout:
                path: security_logout
                target: homepage
            remember_me:
                secret:   "%secret%"
                lifetime: 604800
                path:     /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
